### ISSUE TITLE
Is there an option to use a portable browser in relative path to the app?

### ISSUE THREAD

**Issue by alepodj** [python-eel/Eel#287]
**Is your feature request related to a problem? **
-----
My problem came while trying to deploy an app in an enviroment were i cannot guarantee that Google Chrome will be available and fall back to other browsers wasnt a choice due to app behavior, like: running in app mode, and others. So i decided to ship a portable version of a browser with my app. I started with portable version of Chrome but then moved on a portable version of Brave

**Describe the solution you'd like**
---
Can Brave be added to the list of available defaults since is much like Chrome, and is there or can there be an option to run the selected browser in a relative path to the app

**Describe alternatives you've considered**
---
Electron

**Additional context**
---
To fit my purpose i modified ```browsers.py```  open function and added an extra ```elif``` to match my need as below:

```
elif mode == 'brave':
        for url in start_urls:
            brave_path="brave79/brave-portable.exe"
            wbr.register('brave-portable', None, wbr.BackgroundBrowser(brave_path))
            wbr.get('brave-portable').open('--app=' + url)
```

Cant say if this would be the best or most efficient way but works for my purpose

Cheers

**Comment by SDAMedia** [comment]
can you show me how you do this..
because i install pip eel in python i have no browsers.py 

can you help me step by step..

Thankyou very much..

**Comment by alepodj** [comment]
Hi, regardless of whether u installed EEL in a virtual environment or in the default python directory, this will require the modification of EEL files themselves and eel install should have created a an eel directory that in whichever location python was installed, something like ```<python_path>\Lib\site-packages\eel``` and inside there should be a ```browser.py``` file. In said file there is a open function: `def open(start_pages, options):` with a setups up the browser to be used when the application opens, either with whichever browser the app has configured or ultimately defaulting to the system default browser.

I downloaded a portable Brave browser copy( google it ;) ) and placed it in a folder on a relative path to my entry or my app script, meaning right in the same folder as your app.py or main.py whatever u called it, doesn't have to be this way since u can specific the path to the portable browser executable in the next part but made sense to me. 

In the ```browser.py``` file inside the `def open(start_pages, options):` function insert an ```elif``` as below:
```
elif mode == 'brave':
        for url in start_urls:
            brave_path="brave79/brave-portable.exe"
            wbr.register('brave-portable', None, wbr.BackgroundBrowser(brave_path))
            wbr.get('brave-portable').open('--app=' + url)
```

My choice of Brave was just an example the same could potentially be done with any portable browser, but your mileage may vary. The most important thing here is the path the browser ```.exe``` and the ```mode=='<some_name>'``` which is the name u will use to tell EEL to use this browser on this path and u do this when u initialize your EEL app, example:
```
eel.start(
        'main.html',
        mode='brave'  # Or whichever name u created at mode=='<some_name>' froim before
...
) 
```

Hope that helps provide some extra details

**Comment by SDAMedia** [comment]
hi @alepodj Thankyou very much..
it's working now..
