### ISSUE TITLE
Deleting Cache & Auto-Complete

### ISSUE THREAD

**Issue by blessedcoolant** [python-eel/Eel#510]
So I noticed that the cache of the application and auto-complete suggestions for input fields persist across sessions and applications. I am guessing this is because it uses on the on system chrome engine.

I was wondering if there was a way to isolate this to the sessions of Eel that I have going on. And if there is a way to fully disable caching here without affecting the main chrome browser on the system?

I'm guessing it might be one of the Chrome flags but I am not sure which one. Any help would be appreciated. Thank you.

**Comment by mosindy** [comment]
`--disk-cache-dir=/dev/null`  (should work in windows too even thought it doesn't exist)
You can add ` autocomplete="off"` to the form tag to disable autocomplete.

**Comment by blessedcoolant** [comment]
> `--disk-cache-dir=/dev/null` (should work in windows too even thought it doesn't exist)
> You can add ` autocomplete="off"` to the form tag to disable autocomplete.

Thank you. I'll try that. Also is there a way to actually delete the cache? Or even better, load a custom build of the chromedriver from a local folder instead of using the installed version.
