### ISSUE TITLE
How to get rid of the "Upload x files to this site?" Chrome popup?

### ISSUE THREAD

**Issue by vimevim** [python-eel/Eel#608]
**Describe the problem**
I am trying to select a folder with HTML input tag but chrome gives me a popup that I don't like to see. I just need the folder path, nothing else... I tried Tkinter filedialog but it is not cool with my situation. I searched for a chrome flag to disable this popup but couldn't figure it out. I really need help. 

Here is the screenshot of the popup. I want to disable this one and directly upload the folder name.

![chrome_TDQiG9iT8O](https://user-images.githubusercontent.com/13135006/189412835-581c26f3-b46d-4587-b3d8-502fa8aeef1d.png)

- [x] I know that if I don't provide sample code that allows someone to quickly step into my shoes, I may not get the help I want or my issue may be closed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 103

**Comment by dstricks** [comment]
Eel relies completely on the underlying browser to render the HTML and execute the JavaScript; it doesn't have hooks into any specific browser implementation nor can influence the rendering of HTML or the execution of JavaScript except through command-line start flags or environment variables (when the browser supports them).

If tkinter doesn't work for you and you can't find any Chrome flag or environment variable to change the behavior that you dislike, perhaps you can look for another lightweight Python GUI toolkit to use in lieu of tkinter for getting that file path?

**Comment by vimevim** [comment]
Thanks for your answer, I'm planning to use Tkinter or plyer to do this and freeze the UI until filedialog to close.
