### ISSUE TITLE
How can I save data to users computer? 

### ISSUE THREAD

**Issue by nh916** [python-eel/Eel#611]
**Describe the problem**
I want to save data to users computer when they are using the executable, so that when they close it and launch it later their data still exists. How can I accomplish this?

**Comment by dstricks** [comment]
> How can I accomplish this?

What have you already tried?

**Comment by JustasKud** [comment]
I personally use JSON files for this. Just create a file inside the same directory as the compiled code and edit it using python. Not sure if this is the best option, but it's the one I'm most familiar with.

**Comment by tripleo1** [comment]
Show some code 😉

**Comment by gh-adithya** [comment]
Hi! I would like to work on this issue as my first contribution for the project. Could you help me get started by giving me some pointers so that I can head in the right direction?
