### ISSUE TITLE
 How does eel prohibit f12 from viewing source code

### ISSUE THREAD

**Issue by zhenzi0322** [python-eel/Eel#633]
How does eel prohibit f12 from viewing source code

**Comment by anay-p** [comment]
Since Eel uses a browser to render the website, I don't think there is any real way to completely prevent the user from accessing the source code. Still, if you want to stop the user from being able to use the F12 key specifically, you could do something like:
```javascript
document.addEventListener("keydown", (event) => {
    if (event.key == "F12") {
        event.preventDefault()
    }
})
```
