### ISSUE TITLE
How to find the port number when ``port=0`` is used

### ISSUE THREAD

**Issue by proneon267** [python-eel/Eel#672]
**Describe the problem**
When ``port=0`` is used, it chooses a random port number. So, how do I get the actual port number on which eel is listening?

**Comment by johnegnatis** [comment]
If anybody is still having this issue, the solution was very simple.
 
In your javascript:
eel.set_host(window.location.origin);

**Comment by proneon267** [comment]
I meant to get the port number in the python side. I ended up writing a custom function that returned an unused port and assigned eel to run on it.

**Comment by johnegnatis** [comment]
> I meant to get the port number in the python side. I ended up writing a custom function that returned an unused port and assigned eel to run on it.

How did you get the port in Javascript if I may ask?

**Comment by proneon267** [comment]
You can simply pass the generated port number from python side to the js side through eel object.
