### ISSUE TITLE
eel process will close after web page hot refresh

### ISSUE THREAD

**Issue by ILG2021** [python-eel/Eel#710]
I use the react template in the example, I found that every time the page hot refreshed, the eel process is also close so that i need to restart it. it is very time wasting. Can you fix it?

**Comment by emilioh93** [comment]
Any news? @ILG2021 I'm currently having a worse problem, and that is that when I start the eel process, then I refresh the browser, but it automatically closes the eel process. This does not allow me to work

**Comment by thatfloflo** [comment]
Have you tried to increase the *shutdown_delay* (one of the arguments to `eel.start()`?

**Comment by ILG2021** [comment]
> Have you tried to increase the _shutdown_delay_ (one of the arguments to `eel.start()`?

I will tried later.
