### ISSUE TITLE
Entering size(<width>, <height>) in eel.start() doesn't really work.

### ISSUE THREAD

**Issue by norwagov** [python-eel/Eel#713]
**Eel version**
I'm using **0.16.0** EEL version.

**Describe the bug**
When I try to create any app using **eel**, i cannot use:

```python
eel.init('assets')
eel.start('github_issue.html', size=(500, 500), port=2023)
```
...because the effect looks like this:

![image](https://github.com/python-eel/Eel/assets/60919100/e25bc5b1-972e-4c96-baec-8848e5bfc41c)

Well, as you can see from the code, it should be smaller.

**To Reproduce**
1. Install *eel* using *pip*
2. Create `main.py` file
3. In the same directory as `main.py`, create `assets` folder
4. In the assets folder, create a file called `index.html`, and put some code in it. I've just put a pure string for test.
5. In the main.py, enter the code given down bellow:

```python
import eel

eel.init('assets')
eel.start('index.html', size=(500, 500), port=2023)
```

6. Enter `python -u <directory>/main.py` in terminal / Execute the python file

**Expected behavior**
The window should be 500px by 500px. Well, it's not.

**System Information**
 - OS: *EndeavourOS*
 - Browser: *Application opens with the **Chrome** icon, but i use Firefox*
 - Python Distribution: *Python 3.11.5*

**Comment by thatfloflo** [comment]
This might be a limitation of your browser and OS. Usually with Chrome in app mode the sizing works, but generally most browsers now do not let the user programmatically resize windows, least not without user interaction triggering this. You can try window.resizeTo() in JavaScript and see if that works.

It is using Chrome by default if the *mode* argument to `eel.start()` is not given. Firefox isn't specifically supported at this time, you'd have to do this with `mode='custom'`.

**Comment by norwagov** [comment]
Okay, it works on another OS. Thank You for the help!
