### ISSUE TITLE
Memory leak using Eel

### ISSUE THREAD

**Issue by plg01** [python-eel/Eel#719]
I’m trying to display values on an HTML page from data coming from a python script. It’s working but I have a leak memory issue and I don’t know why. Below my code.
My js file receives well the list “data” from my python file but the size of Chrome displaying the HTML page is increasing continuously.
Does somebody know what and where is the issue ?

Python code :
```python
import eel

data = [0]*7200


@eel.expose
def get_Graph():
    return data
```

JS code :
```js
function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

startTime()

async function startTime(){
    while (true){
        let data_from_python = await eel.get_Graph()();
        // ...
        await sleep(10);
    }
}
    
 
```

**System Information**

OS: Windows 10
Browser: Chrome 114.0.5735.110
Python Distribution: Python 3.11

**Comment by Xanderplayz16** [comment]
It's probably a Chrome problem.

**Comment by plg01** [comment]
I have no more the problem, the software have been running 18 hours and no memory leak. I haven't done somethings special, I'm working on a professionnal laptop so maybe an Chrome update solved my problem (currently in version Version 122.0.6261.112 (Build officiel) (64 bits) )
