### ISSUE TITLE
Custom Route Configuration

### ISSUE THREAD

**Issue by Utsav-patell** [python-eel/Eel#720]
I would like the addition of a feature that allows developers to set custom routes for their applications easily. Having the ability to configure routes programmatically would provide greater flexibility in designing the application's navigation structure. 
Also if there is already a method present for this then please help me. I am new to eel

**Comment by samuelhwilliams** [comment]
You should be able to expose routes programmatically/dynamically already. `eel.expose` can be used as a decorator, or just as a function - so you could call it in a loop, or in response to some input, or anything. Hope that helps.

**Comment by Utsav-patell** [comment]
> You should be able to expose routes programmatically/dynamically already. `eel.expose` can be used as a decorator, or just as a function - so you could call it in a loop, or in response to some input, or anything. Hope that helps.

Ohk...thanks for the reply finally 😁.

**Comment by samuelhwilliams** [comment]
Sorry for the absence :(
