### ISSUE TITLE
ModuleNotFoundError: No module named 'bottle.ext.websocket'       

### ISSUE THREAD

**Issue by aryantricks** [python-eel/Eel#723]
ModuleNotFoundError: No module named 'bottle.ext.websocket'       

i cant figure why this happening

**Comment by Slluxx** [comment]
In eel's __init__.py, replace the import line that contains `bottle.ext.websocket` with `import bottle_websocket as wbs`

**Comment by JonathanAriass** [comment]
> In eel's `__init__.py`, replace the import line that contains `bottle.ext.websocket` with `import bottle_websocket as wbs`
I found.

**Comment by samuelhwilliams** [comment]
Fixed by https://github.com/python-eel/Eel/pull/725
