### ISSUE TITLE
My eel application blocking the chrome running while is run. 

### ISSUE THREAD

**Issue by AndreyMayantsev** [python-eel/Eel#726]
My eel application blocking the chrome running while is run.

**Comment by grizn1** [comment]
I was able to work around it by creating a separate user profile on the command line.
(Sorry for the translated text.)
    
    
    user_data_dir = os.path.join(os.getcwd(), "chrome_user_data")

    eel_kwargs = dict(
        mode="chrome",
        host="localhost",
        port=8888,
        size=(1000, 800),
        cmdline_args=[
            f"--user-data-dir={user_data_dir}",
        ],
        block=False,
    )
    
   eel.start(page, **eel_kwargs)

**Comment by AndreyMayantsev** [comment]
Thank you
